// STORIGN ALL CONSTANTS FOR ACTIONS
export const CHANGE_IMAGE_URL = 'CHANGE_IMAGE_URL';

export const USER_REQUEST_PENDING = 'USER_REQUEST_PENDING';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAIL = 'USER_REQUEST_FAIL';